export const experienceData = {
  work: [
    {
      company: 'Fynz IQ',
      href: 'https://www.fynz.tax/',
      logo: '/fynz-logo.avif',
      role: 'Full-Stack Developer and GoHighLevel Specialist',
      type: 'Part-time',
      dateRange: 'Jul 2026 – Present',
      bullets: [],
      badges: [],
    },
    {
      company: 'Nodd Solutions',
      href: 'https://noddsolutions.com/',
      logo: '/nodd_solutionsjpg.jpg',
      role: 'Full Stack Developer and CRM Specialist',
      type: '',
      dateRange: 'Nov 2024 – Nov 2025',
      bullets: [],
      badges: [],
    },
    {
      company: 'Pluto Technologies',
      href: 'https://plutotechnologies.org/',
      logo: '/pluto_logo.jpg',
      role: 'Backend Developer',
      type: '',
      dateRange: 'Feb 2024 – Nov 2024',
      bullets: [],
      badges: [],
    },
    {
      company: 'Freelance',
      logo: '🚀',
      role: 'Full Stack Developer',
      type: '',
      dateRange: 'Nov 2025 – Present',
      bullets: [],
      badges: [],
    },
  ],
  education: [
    {
      company: 'Addis Ababa Science and Technology University',
      logo: '/aastu_logo.jpg',
      role: 'Bachelor of Software Engineering',
      type: '',
      dateRange: 'May 2022 – Jun 2026',
      bullets: [],
      badges: [],
    },
    {
      company: 'Lideta Catholic Cathedral School',
      logo: '/lideta-catholic-cathedral-school.png',
      role: 'High School Diploma',
      type: '',
      dateRange: 'Sep 2019 – Sep 2021',
      bullets: [],
      badges: [],
    },
  ],
};
