export const experienceData = {
  work: [
    {
      company: 'Fynz IQ',
      href: 'https://www.fynz.tax/',
      logo: '/fynz-logo.avif',
      role: 'Full-Stack Developer and GoHighLevel Specialist',
      type: 'Part-time',
      location: 'Toronto, Canada',
      dateRange: 'Jul 2026 – Present',
      bullets: [],
      badges: [],
    },
    {
      company: 'Nodd Solutions',
      href: 'https://noddsolutions.com/',
      logo: '/nodd_solutionsjpg.jpg',
      role: 'Lead Full-Stack Developer',
      type: 'Remote',
      location: 'Sydney, Australia',
      dateRange: 'Nov 2024 – Nov 2026',
      bullets: [],
      badges: [],
    },
    {
      company: 'Pluto Technologies',
      href: 'https://plutotechnologies.org/',
      logo: '/pluto_logo.jpg',
      role: 'Backend Engineer',
      type: '',
      location: 'Addis Ababa, Ethiopia',
      dateRange: 'Feb 2024 – Nov 2024',
      bullets: [],
      badges: [],
    },
    {
      company: 'Google Developers Students Club',
      href: null,
      logo: '/gdsc_logo.svg',
      role: 'Laravel Mentorship',
      type: '',
      location: 'AASTU',
      dateRange: 'Jan 2023 – Jan 2024',
      bullets: [],
      badges: [],
    },
  ],
  education: [
    {
      company: 'Addis Ababa Science and Technology University',
      logo: '/aastu_logo.jpg',
      role: 'Bachelor of Software Engineering',
      type: 'Software Engineering',
      location: 'Addis Ababa, Ethiopia',
      dateRange: 'May 2022 – Jun 2026',
      bullets: [],
      badges: [],
    },
    {
      company: 'Lideta Catholic Cathedral School',
      logo: '/lideta-catholic-cathedral-school.png',
      role: 'High School Diploma',
      type: 'Natural Sciences',
      location: 'Addis Ababa, Ethiopia',
      dateRange: 'Sep 2019 – Aug 2021',
      bullets: [],
      badges: [],
    },
  ],
};
