export const experienceData = {
  work: [
    {
      company: 'Fynz IQ',
      href: 'https://www.fynz.tax/',
      logo: '/fynz-logo.avif',
      role: 'Full-Stack Developer and GoHighLevel Specialist',
      type: 'Part-time',
      dateRange: 'Jul 2026 – Present',
      bullets: [],
      badges: [],
    },
    {
      company: 'Nodd Solutions',
      href: 'https://noddsolutions.com/',
      logo: '/nodd_solutionsjpg.jpg',
      role: 'Full Stack Developer and CRM Specialist',
      type: '',
      dateRange: 'Nov 2024 – Nov 2025',
      bullets: [],
      badges: [],
    },
    {
      company: 'Pluto Technologies',
      href: 'https://plutotechnologies.org/',
      logo: '/pluto_logo.jpg',
      role: 'Backend Developer',
      type: '',
      dateRange: 'Feb 2024 – Nov 2024',
      bullets: [],
      badges: [],
    },
    {
      company: 'Freelance',
      logo: '🚀',
      role: 'Full Stack Developer',
      type: '',
      dateRange: 'Nov 2025 – Present',
      bullets: [
        'Building end-to-end web and mobile applications for international clients using React, Next.js, Node.js, and React Native.',
        'Architecting scalable RESTful APIs, database schemas, and responsive user interfaces.',
      ],
      badges: [],
    },
  ],
  education: [
    {
      company: 'Addis Ababa Science and Technology University',
      logo: '/aastu_logo.jpg',
      role: 'Bachelor of Software Engineering',
      type: '',
      dateRange: 'May 2022 – Jun 2026',
      bullets: [
        'Pursuing Bachelor of Science in Software Engineering with focus on software architecture, algorithms, and data structures.',
        'Completed coursework in web and mobile systems, distributed computing, database design, and software testing.',
        'Collaborated on multiple team software development projects applying agile methodologies.',
      ],
      badges: [],
    },
    {
      company: 'Lideta Catholic Cathedral School',
      logo: '/lideta-catholic-cathedral-school.png',
      role: 'High School Diploma',
      type: '',
      dateRange: 'Sep 2019 – Sep 2021',
      bullets: [
        'Completed secondary school curriculum with focus on natural sciences, mathematics, and foundational computing.',
        'Active participant in academic clubs and technology-oriented student activities.',
      ],
      badges: [],
    },
  ],
};
